def letter_embeds
  {
    'A' => 'img/air.svg',
    'F' => 'img/fire.svg',
    'P' => 'img/plant.svg',
    'S' => 'img/stone.svg',
    'W' => 'img/water.svg',
    # 'B' => 'img/balloon.svg',
    # 'E' => 'img/mine.svg',
    # 'G' => 'img/grow.svg',
    # 'H' => 'img/hike.svg',
    # 'L' => 'img/worker.svg',
    # 'M' => 'img/meeple.svg',
    # 'R' => 'img/mage.svg',
    # 'T' => 'img/sow.svg',
    # 'Z' => 'img/research.svg',
  }
end

def key_embeds
  {
    ':2xlibrary:' =>        'img/2xlibrary.svg',
    ':air:' =>              'img/air.svg',
    ':airfield:' =>         'img/airfield.svg',
    ':balloon:' =>          'img/balloon.svg',
    ':bet:' =>              'img/bet.svg',
    ':burning:' =>          'img/burning.svg',
    ':confusion:' =>        'img/confusion.svg',
    ':controlled-burns:' => 'img/controlled-burns.svg',
    ':dig:' =>              'img/dig.svg',
    ':fire:' =>             'img/fire.svg',
    ':forge:' =>            'img/forge.svg',
    ':gamble:' =>           'img/gamble.svg',
    ':gate:' =>             'img/gate.svg',
    ':grow:' =>             'img/grow.svg',
    ':hike:' =>             'img/hike.svg',
    ':hospital:' =>         'img/hospital.svg',
    ':mage-income:' =>      'img/mage-income.svg',
    ':mage:' =>             'img/mage.svg',
    ':meeple:' =>           'img/meeple.svg',
    ':mine:' =>             'img/mine.svg',
    ':potent:' =>           'img/potent.svg',
    ':plant:' =>            'img/plant.svg',
    ':research:' =>         'img/research.svg',
    ':rooted:' =>           'img/rooted.svg',
    ':scout:' =>            'img/scout.svg',
    ':seed:' =>             'img/seed.svg',
    ':spell:' =>            'img/spell.svg',
    ':sprinkler:' =>        'img/sprinkler.svg',
    ':stone:' =>            'img/stone.svg',
    ':water-income:' =>     'img/water-income.svg',
    ':water:' =>            'img/water.svg',
    ':worker-income:' =>    'img/worker-income.svg',
    ':worker:' =>           'img/worker.svg',
  }
end