LETTER_EMBEDS = {
  'A' => 'img/air.svg',
  'B' => 'img/balloon.svg',
  # 'C' => 'img/craft.svg',
  'D' => 'img/decipher.svg',
  'E' => 'img/mine.svg',
  'F' => 'img/fire.svg',
  'G' => 'img/grow.svg',
  'H' => 'img/hike.svg',
  'L' => 'img/laborers.svg',
  'M' => 'img/meeple.svg',
  'P' => 'img/plant.svg',
  'R' => 'img/apprentice.svg',
  'S' => 'img/stone.svg',
  'T' => 'img/sow.svg',
  'W' => 'img/water.svg',
  'Z' => 'img/research.svg',
}
def key_embeds
  {
    ':air:' => 'img/air.svg',
    ':balloon:' => 'img/balloon.svg',
    ':forge:' => 'img/forge.svg',
    ':decipher:' => 'img/decipher.svg',
    ':mine:' => 'img/mine.svg',
    ':fire:' => 'img/fire.svg',
    ':grow:' => 'img/grow.svg',
    ':hike:' => 'img/hike.svg',
    ':laborers:' => 'img/laborers.svg',
    ':meeple:' => 'img/meeple.svg',
    ':plant:' => 'img/plant.svg',
    ':mage:' => 'img/apprentice.svg',
    ':scout:' => 'img/scout.svg',
    ':stone:' => 'img/stone.svg',
    ':spell:' => 'img/spell.svg',
    ':sow:' => 'img/sow.svg',
    ':water:' => 'img/water.svg',
    ':research:' => 'img/research.svg',
  }
end