def letter_embeds
  {
    'A' => 'img/air.svg',
    'F' => 'img/fire.svg',
    'P' => 'img/plant.svg',
    'S' => 'img/stone.svg',
    'W' => 'img/water.svg',
    # 'B' => 'img/balloon.svg',
    # 'E' => 'img/mine.svg',
    # 'G' => 'img/grow.svg',
    # 'H' => 'img/hike.svg',
    # 'L' => 'img/worker.svg',
    # 'M' => 'img/meeple.svg',
    # 'R' => 'img/mage.svg',
    # 'T' => 'img/sow.svg',
    # 'Z' => 'img/research.svg',
  }
end

def key_embeds
  {
    ':air:' => 'img/air.svg',
    ':balloon:' => 'img/balloon.svg',
    ':forge:' => 'img/forge.svg',
    ':mine:' => 'img/mine.svg',
    ':fire:' => 'img/fire.svg',
    ':grow:' => 'img/grow.svg',
    ':hike:' => 'img/hike.svg',
    ':worker:' => 'img/worker.svg',
    ':meeple:' => 'img/meeple.svg',
    ':plant:' => 'img/plant.svg',
    ':mage:' => 'img/mage.svg',
    ':scout:' => 'img/scout.svg',
    ':stone:' => 'img/stone.svg',
    ':spell:' => 'img/spell.svg',
    ':sow:' => 'img/sow.svg',
    ':water:' => 'img/water.svg',
    ':research:' => 'img/research.svg',
    ':gamble:' => 'img/gamble.svg',
    ':water-income:' => 'img/water-income.svg',
    # ':worker-income:' => 'img/worker-income.svg',
    # ':mage-income:' => 'img/mage-income.svg',
    # ':sprinker:' => 'img/sprinker.svg',
    # ':bet:' => 'img/bet.svg',
    # ':water-tower:' => 'img/water-tower.svg',
    # ':controlled-burns:' => 'img/controlled-burns.svg',
    # ':seed:' => 'img/seed.svg',
    # ':elite-recon:' => 'img/elite-recon.svg',
  }
end